config/routes.rb
Rails.application.routes.draw do
  get ':id/stats' => 'urls#stats', as: :stats
  get ':id' => 'urls#goto', as: :goto
  resources :urls , only: [:new , :create, :update, :index, :edit]

  root 'urls#new'

end

app/models/info.rb
class Info < ActiveRecord::Base
  serialize :raw
  belongs_to :urls

  def location
    loc  = Geokit::Geocoders::MultiGeocoder.geocode(self.raw[:ip])
    {country: loc.country_code, state: loc.state, city: loc.city}
  end
  def browser_name
    browser = Browser.new(:ua => self.raw[:ua])
    browser.name
  end
  def browser_platform
    browser = Browser.new(:ua => self.raw[:ua])
    browser.platform
  end
end

app/models/url.rb
class Url < ActiveRecord::Base
  has_many :infos
  validates :origin, presence:  true
  validates :short, presence:  true
  validates :origin, :uniqueness => true
  validates :short, :uniqueness => true
  validates_format_of :short, :with => /\A[A-Za-z0-9]*\z/
  #before_create :compile
  before_validation :format_origin

  def compile
    self.short = Digest::SHA1.hexdigest([self.origin, rand].join)[1..5]
  end
  def format_origin
    unless self.origin.blank?
      self.origin.slice!(/http:\/\/|https:\/\//)
      self.origin = "http://#{self.origin}"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: [:edit, :update, :destroy, :stats, :goto]

  # GET /urls
  # GET /urls.json
  def index
    @urls = Url.all
  end

  # GET /urls/1
  # GET /urls/1.json
  def stats
  end


  # GET /urls/new
  def goto
    #save request and useragent
    @url.infos.create(raw: {ip: request.remote_ip, ua: request.env["HTTP_USER_AGENT"]})
    redirect_to @url.origin, :status => 301
  end

  def new
    @url = Url.new
  end

  # GET /urls/1/edit
  def edit
  end

  # POST /urls
  # POST /urls.json
  def create
    @url = Url.new(url_params)
    respond_to do |format|
      if @url.save
        format.html { redirect_to stats_path(id: @url.short), notice: 'Url was successfully created.' }
        format.json { render :show, status: :created, location: @url }
      else
        format.html { render :new }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /urls/1
  # PATCH/PUT /urls/1.json
  def update
    respond_to do |format|
      if @url.update(url_params)
        format.html { redirect_to @url, notice: 'Url was successfully updated.' }
        format.json { render :show, status: :ok, location: @url }
      else
        format.html { render :edit }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1
  # DELETE /urls/1.json
  def destroy
    @url.destroy
    respond_to do |format|
      format.html { redirect_to urls_url, notice: 'Url was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find_by(short: params[:id])
      redirect_to  root_path , notice: 'Url not foud, u can create it!' if  @url.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def url_params
      #just origin n infos
      params.require(:url).permit(:origin, :short)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pendek</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/urls/_form.html.erb
<%= form_for(@url) do |f| %>
  <% if @url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
      <% @url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :origin %><br>
    <%= f.text_field :origin %>
  </div>
  <div class="field">
    <%= f.label :short %><br>
    <%= f.text_field :short %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/urls/edit.html.erb
<h1>Editing Url</h1>

<%= render 'form' %>

<%= link_to 'Show', stats_path(id: @url.short) %> |
<%= link_to 'Create', urls_path %>

app/views/urls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Urls</h1>

<table>
  <thead>
    <tr>
      <th>Origin</th>
      <th>Short</th>
      <th>Infos</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <td><%= url.origin %></td>
        <td><%= url.short %></td>
        <td><%= url.infos %></td>
        <td><%= link_to 'Show', url %></td>
        <td><%= link_to 'Edit', edit_url_path(url) %></td>
        <td><%= link_to 'Destroy', url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Url', new_url_path %>

app/views/urls/new.html.erb
<h1>New Url</h1>
<p id="notice"><%= notice %></p>
<%= render 'form' %>

<%= link_to 'Back', urls_path %>

app/views/urls/stats.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Short:</strong>
  <a href="<%= goto_path(id: @url.short) %>" target="_blank"><%= "#{root_url(:only_path => false)}#{@url.short}" %></a>
</p>

<p>
  <strong>Origin:</strong>
  <%= @url.origin %>
</p>

<h2>Info</h2>
<% if @url.infos.present? %>
    <% @url.infos.each do |info| %>
        <p>
          <strong>Infos IP:</strong>
          <%= info.raw[:ip] %>
        </p>

        <p>
          <strong>Infos Location:</strong>
          <%= info.location %>
        </p>
        <p>
          <strong>Infos Browser:</strong>
          <%= info.browser_name %>
        </p>
        <p>
          <strong>Infos Platform:</strong>
          <%= info.browser_platform %>
        </p>

        <p>
          <strong>Infos UA:</strong>
          <%= info.raw[:ua] %>
        </p>
        <p>------------------------------------</p><br/>
    <% end %>

<% else %>
    <p> ---------- empty ---------</p>
    <br/>
<% end %>
<%= link_to 'Create', new_url_path %>